### PR TITLE
Upgrade to Webpack 2.3

### PR DESCRIPTION
**Pull request by AdamJo**
Updated to Webpack 2.3.2 and ready to go.

The majority of commits have details in case you want to read up on the changes made.

edit: lets try this again 😄

### CODE REVIEW

**Comment by developit** [comment]
Awesome - I'm going to test this out locally tonight just to double check everything and then we'll be good to go!

**Comment by AdamJo** [comment]
Pssst @developit we are almost there 😄.  Let me know if you would like me to do anything else.

**Comment by developit** [comment]
I did a local run and I'm seeing all the chunks actually got larger from Webpack 2. Any thoughts as to why that might be?

**Comment by AdamJo** [comment]
I see what you mean, looks like I missed that.  

I think it has something to do with the upgraded version of UglifyJS that comes with Webpack 2.  Using more constraints on UglifyJS I was able to eliminate most of that bulk added.

Before Changes:
    Offline-Plugin / sw.js (723b increase).
    Bundle.js (264b increase).

After Changes: 
    Bundle.js (139b increase)
    Offline-Plugin / sw.js (86b **decrease**).

In total now it is only a 53b increase in size.  Let me know if you would like me to do some more digging around.

**Comment by developit** [comment]
I wonder if the latest webpack update changes these sizes again?

**Comment by AdamJo** [comment]
Updated to Webpack 2.4.1 and Offline-plugin 4.7.0.  No change in build size from either versions.

**Comment by developit** [comment]
@AdamJo I'm good to merge this if we get the conflicts resolved (they are from the Jest migration, should just be deletions).

**Comment by AdamJo** [comment]
@developit Merged and tests are passing. Let me know if you need anything else.

**Comment by developit** [comment]
Let's do this! :)

**Pull request merged**
