### PR TITLE
Update webpack.config.babel.js

### LINKED ISSUE #62: Class is empty when build via Windows
Here's different
On mac (working fine `<header class="header_3fP58">`)
screen shot 2016-09-01 at 22 27 33

``` js
t["default"]=s},function(e,t){},function(e,t){e.exports={header:"header_3fP58"}},function(e,t){e.exports={home:"home_2xyY2"}},function(e,t){e.exports={profile:"profile_JmD9R"}}]);
//# sourceMappingURL=bundle.js.map
```

On Windows (appear `<header class>`)
screen shot 2016-09-01 at 22 27 42

``` js
t["default"]=s},function(e,t){},7,7,7]));
//# sourceMappingURL=bundle.js.map
```

As you can see some export is missing on Windows build, Any idea? Maybe some build script is working only on Mac?

### PR DESCRIPTION
**Pull request by bang88**
fixes #62

### CODE REVIEW

**Comment by bang88** [comment]
@developit Sorry,I am edit this file online. It should works.

**Comment by wuvluv** [comment]
Can confirm this fixes the issue with CSS Modules class names on my Windows 7 pc.

**Comment by developit** [comment]
I'm going to merge this but remove the custom CSS modules aliasing - I think we can actually just switch to using the default, which will really simplify things.  Thanks for debugging this on Windows!

**Comment by bang88** [comment]
Yep.

**Comment by ubershmekel** [comment]
I'm on Windows 10 and can also confirm this PR makes the CSS work.

**Pull request merged**
