### PR TITLE
(chore) Fixes #97

### LINKED ISSUE #97: Probably Invalid Dependency in package.json
On installing packages for boilerplate using yarn I see below warning.

warning preact-boilerplate@5.0.0: Dependency "path" listed in "devDependencies" is the name of a built-in module

which leads me to believe the path is maybe incorrect dependency.

Probably related to https://github.com/jinder/path/issues/6

### PR DESCRIPTION
**Pull request by abhishekisnot**
Please view this PR using ?w=1 URL to see changes -- https://github.com/developit/preact-boilerplate/pull/98/files?w=1

### CODE REVIEW

**Comment by developit** [comment]
The `path` change is good, but why did you include all these whitespace modifications?  Boilerplates aren't a good place to debate tabs VS spaces, and the project is already tabs (with an editorconfig and eslintrc to make it transparent)

**Comment by abhishekisnot** [comment]
Darn. The tab vs spaces change was not intentional. I did not realize subsequent commits to fork do land up in a PR if pr is still open. Let me see how to revert this.

**Comment by developit** [comment]
ahh, that makes sense lol. happy to do the path thing if you just submit via github's web interface if that's easier!

**Comment by abhishekisnot** [comment]
Done.

**Pull request merged**
