### PR TITLE
Switch to Jest + JSX component test examples

### PR DESCRIPTION
**Pull request by KrofDrakula**
I've removed the karma test runner and replaced it with Jest, along with examples of using the built-in JSDOM to test things like mounting components and testing timed events through the Jest-supplied Sinon fake timers.

It's in rough shape, but it does illustrate the harder parts of testing Preact components. The next step would be to produce a test for interaction events.

### CODE REVIEW

**Comment by developit** [comment]
ok I finally checked this out and its awesome. merging.

**Comment by eduardoboucas** [comment]
This is great, thanks! Is it possible to do things like simulate a click and check whether a callback function has been called, or is that something that only React+TestUtils can achieve?

**Comment by KrofDrakula** [comment]
@eduardoboucas There's no built-in functionality, but you can use jQuery or any other DOM utility (probably even TestUtils) to call `dispatchEvent()` on any element. Usually I just write a quick helper function for `click(el)` that will create a `click` event and call `el.dispatchEvent(ev)` on the element. That way I can keep React (and other non-essential libs) out of my codebase when I don't need them.

**Comment by developit** [comment]
@KrofDrakula @eduardoboucas I do the same! My go-to fireEvent is here:
https://gist.github.com/developit/ee1f4ee1de3d538dc2ca6f74ac8fb77d

**Pull request merged**
